export type Product = {
  id: number
  name: string
  category: string
  price: number
  emoji: string
  badge?: "Promo" | "Nouveau"
}

export const products: Product[] = [
  // --- Boulangerie ---
  {
    id: 1,
    name: "Croissant beurre artisanal",
    category: "Boulangerie",
    price: 1.2,
    emoji: "🥐",
    badge: "Promo",
  },
  {
    id: 2,
    name: "Pain de campagne au levain",
    category: "Boulangerie",
    price: 4.5,
    emoji: "🍞",
  },
  {
    id: 3,
    name: "Baguette tradition",
    category: "Boulangerie",
    price: 1.1,
    emoji: "🥖",
  },
  {
    id: 4,
    name: "Pain aux céréales bio",
    category: "Boulangerie",
    price: 3.8,
    emoji: "🍞",
    badge: "Nouveau",
  },
  {
    id: 5,
    name: "Brioche maison",
    category: "Boulangerie",
    price: 5.5,
    emoji: "🧁",
  },

  // --- Épicerie ---
  {
    id: 6,
    name: "Confiture maison framboise",
    category: "Épicerie",
    price: 5.9,
    emoji: "🫙",
  },
  {
    id: 7,
    name: "Miel de lavande artisanal",
    category: "Épicerie",
    price: 8.5,
    emoji: "🍯",
  },
  {
    id: 8,
    name: "Huile d'olive extra vierge",
    category: "Épicerie",
    price: 12.0,
    emoji: "🫒",
    badge: "Promo",
  },
  {
    id: 9,
    name: "Pâtes fraîches aux œufs",
    category: "Épicerie",
    price: 4.2,
    emoji: "🍝",
  },
  {
    id: 10,
    name: "Riz basmati 1kg",
    category: "Épicerie",
    price: 3.6,
    emoji: "🍚",
  },

  // --- Fromagerie ---
  {
    id: 11,
    name: "Comté 18 mois AOP",
    category: "Fromagerie",
    price: 3.8,
    emoji: "🧀",
    badge: "Promo",
  },
  {
    id: 12,
    name: "Brie de Meaux AOP",
    category: "Fromagerie",
    price: 4.5,
    emoji: "🧀",
  },
  {
    id: 13,
    name: "Roquefort AOP",
    category: "Fromagerie",
    price: 5.2,
    emoji: "🧀",
    badge: "Nouveau",
  },
  {
    id: 14,
    name: "Camembert de Normandie",
    category: "Fromagerie",
    price: 3.9,
    emoji: "🧀",
  },
  {
    id: 15,
    name: "Chèvre frais aux herbes",
    category: "Fromagerie",
    price: 2.8,
    emoji: "🧀",
  },

  // --- Boissons ---
  {
    id: 16,
    name: "Café single origin Éthiopie",
    category: "Boissons",
    price: 14.5,
    emoji: "☕",
    badge: "Nouveau",
  },
  {
    id: 17,
    name: "Bordeaux rouge Château Blanc",
    category: "Boissons",
    price: 12.0,
    emoji: "🍷",
  },
  {
    id: 18,
    name: "Jus de pomme pressé maison",
    category: "Boissons",
    price: 4.8,
    emoji: "🍎",
  },
  {
    id: 19,
    name: "Thé vert Sencha bio",
    category: "Boissons",
    price: 9.5,
    emoji: "🍵",
    badge: "Nouveau",
  },
  {
    id: 20,
    name: "Bière artisanale IPA locale",
    category: "Boissons",
    price: 3.5,
    emoji: "🍺",
    badge: "Promo",
  },

  // --- Électronique ---
  {
    id: 21,
    name: "Casque audio sans fil",
    category: "Électronique",
    price: 79.99,
    emoji: "🎧",
    badge: "Promo",
  },
  {
    id: 22,
    name: "Chargeur USB-C 65W",
    category: "Électronique",
    price: 29.99,
    emoji: "🔌",
  },
  {
    id: 23,
    name: "Enceinte Bluetooth portable",
    category: "Électronique",
    price: 49.99,
    emoji: "🔊",
    badge: "Nouveau",
  },
  {
    id: 24,
    name: "Clé USB 64Go USB 3.0",
    category: "Électronique",
    price: 12.99,
    emoji: "💾",
  },
  {
    id: 25,
    name: "Câble HDMI 2m 4K",
    category: "Électronique",
    price: 9.99,
    emoji: "📺",
  },
  {
    id: 26,
    name: "Souris sans fil ergonomique",
    category: "Électronique",
    price: 34.99,
    emoji: "🖱️",
    badge: "Promo",
  },
  {
    id: 27,
    name: "Lampe de bureau LED",
    category: "Électronique",
    price: 24.99,
    emoji: "💡",
    badge: "Nouveau",
  },
  {
    id: 28,
    name: "Batterie externe 20000mAh",
    category: "Électronique",
    price: 39.99,
    emoji: "🔋",
  },
  {
    id: 29,
    name: "Webcam Full HD 1080p",
    category: "Électronique",
    price: 59.99,
    emoji: "📷",
  },
  {
    id: 30,
    name: "Hub USB 7 ports",
    category: "Électronique",
    price: 19.99,
    emoji: "🔌",
    badge: "Nouveau",
  },

  // --- Musique ---
  {
    id: 31,
    name: "Médiators guitare (pack 12)",
    category: "Musique",
    price: 4.99,
    emoji: "🎸",
  },
  {
    id: 32,
    name: "Cordes guitare acoustique",
    category: "Musique",
    price: 8.5,
    emoji: "🎸",
    badge: "Promo",
  },
  {
    id: 33,
    name: "Métronome numérique",
    category: "Musique",
    price: 14.99,
    emoji: "🎵",
  },
  {
    id: 34,
    name: "Pupitre de partition pliable",
    category: "Musique",
    price: 19.99,
    emoji: "🎼",
  },
  {
    id: 35,
    name: "Câble Jack 6.35mm 3m",
    category: "Musique",
    price: 7.99,
    emoji: "🎚️",
  },
  {
    id: 36,
    name: "Housse piano clavier 61 touches",
    category: "Musique",
    price: 22.0,
    emoji: "🎹",
    badge: "Nouveau",
  },
  {
    id: 37,
    name: "Capo guitare aluminium",
    category: "Musique",
    price: 9.99,
    emoji: "🎸",
  },
  {
    id: 38,
    name: "Sangle guitare réglable",
    category: "Musique",
    price: 11.5,
    emoji: "🎸",
    badge: "Promo",
  },
  {
    id: 39,
    name: "Accordeur chromatique clip",
    category: "Musique",
    price: 6.99,
    emoji: "🎵",
  },
  {
    id: 40,
    name: "Cahier de partitions vierge",
    category: "Musique",
    price: 3.5,
    emoji: "🎼",
  },

  // --- Mobilier ---
  {
    id: 41,
    name: "Chaise de bureau ergonomique",
    category: "Mobilier",
    price: 189.0,
    emoji: "🪑",
    badge: "Promo",
  },
  {
    id: 42,
    name: "Étagère murale en bois 80cm",
    category: "Mobilier",
    price: 45.0,
    emoji: "🪵",
    badge: "Nouveau",
  },
  {
    id: 43,
    name: "Lampadaire scandinave",
    category: "Mobilier",
    price: 69.0,
    emoji: "💡",
  },
  {
    id: 44,
    name: "Bureau en L 120x80cm",
    category: "Mobilier",
    price: 249.0,
    emoji: "🪑",
    badge: "Promo",
  },
  {
    id: 45,
    name: "Miroir rond 60cm",
    category: "Mobilier",
    price: 39.0,
    emoji: "🪞",
  },
  {
    id: 46,
    name: "Table basse bois et métal",
    category: "Mobilier",
    price: 129.0,
    emoji: "🪵",
    badge: "Nouveau",
  },
  {
    id: 47,
    name: "Tabouret bar industriel",
    category: "Mobilier",
    price: 55.0,
    emoji: "🪑",
  },
  {
    id: 48,
    name: "Cintre mural 5 crochets",
    category: "Mobilier",
    price: 18.0,
    emoji: "🪝",
  },
  {
    id: 49,
    name: "Pouf rond velours gris",
    category: "Mobilier",
    price: 49.0,
    emoji: "🛋️",
    badge: "Promo",
  },
  {
    id: 50,
    name: "Cadre photo galerie 30x40",
    category: "Mobilier",
    price: 14.0,
    emoji: "🖼️",
  },

  // --- Librairie ---
  {
    id: 51,
    name: "Atomic Habits – J. Clear",
    category: "Librairie",
    price: 18.9,
    emoji: "📗",
    badge: "Promo",
  },
  {
    id: 52,
    name: "Le Monde selon Garp",
    category: "Librairie",
    price: 9.5,
    emoji: "📘",
  },
  {
    id: 53,
    name: "Clean Code – R. Martin",
    category: "Librairie",
    price: 35.0,
    emoji: "📙",
    badge: "Nouveau",
  },
  {
    id: 54,
    name: "Petit Prince – illustré",
    category: "Librairie",
    price: 7.9,
    emoji: "📕",
  },
  {
    id: 55,
    name: "Carnet de notes A5 toilé",
    category: "Librairie",
    price: 11.0,
    emoji: "📓",
  },
  {
    id: 56,
    name: "Stylos gel noir (lot 5)",
    category: "Librairie",
    price: 6.5,
    emoji: "✒️",
    badge: "Promo",
  },
  {
    id: 57,
    name: "Agenda 2026 semainier",
    category: "Librairie",
    price: 14.0,
    emoji: "📅",
    badge: "Nouveau",
  },
  {
    id: 58,
    name: "Post-it multicolores (pack)",
    category: "Librairie",
    price: 5.2,
    emoji: "🗒️",
  },
  {
    id: 59,
    name: "Dictionnaire Larousse 2025",
    category: "Librairie",
    price: 28.0,
    emoji: "📚",
  },
  {
    id: 60,
    name: "Marqueurs fluo (lot 6)",
    category: "Librairie",
    price: 4.8,
    emoji: "✏️",
  },

  // --- Sport ---
  {
    id: 61,
    name: "Gourde inox 750ml",
    category: "Sport",
    price: 19.99,
    emoji: "🫗",
    badge: "Promo",
  },
  {
    id: 62,
    name: "Tapis de yoga antidérapant",
    category: "Sport",
    price: 29.99,
    emoji: "🧘",
    badge: "Nouveau",
  },
  {
    id: 63,
    name: "Corde à sauter pro",
    category: "Sport",
    price: 12.0,
    emoji: "🪢",
  },
  {
    id: 64,
    name: "Bandes de résistance (lot 3)",
    category: "Sport",
    price: 16.5,
    emoji: "💪",
  },
  {
    id: 65,
    name: "Chaussettes running anti-ampoules",
    category: "Sport",
    price: 9.9,
    emoji: "🧦",
    badge: "Promo",
  },
  {
    id: 66,
    name: "Roller massage foam",
    category: "Sport",
    price: 22.0,
    emoji: "🔵",
  },
  {
    id: 67,
    name: "Bidon vélo 500ml",
    category: "Sport",
    price: 7.5,
    emoji: "🚴",
  },
  {
    id: 68,
    name: "Poignées de traction",
    category: "Sport",
    price: 18.0,
    emoji: "💪",
    badge: "Nouveau",
  },
  {
    id: 69,
    name: "Protège-poignets skate",
    category: "Sport",
    price: 14.0,
    emoji: "🛹",
  },
  {
    id: 70,
    name: "Sac à dos sport 20L",
    category: "Sport",
    price: 34.99,
    emoji: "🎒",
    badge: "Promo",
  },

  // --- Maison & Cuisine ---
  {
    id: 71,
    name: "Planche à découper bambou",
    category: "Cuisine",
    price: 19.9,
    emoji: "🍽️",
  },
  {
    id: 72,
    name: "Couteau chef 20cm japonais",
    category: "Cuisine",
    price: 44.0,
    emoji: "🔪",
    badge: "Nouveau",
  },
  {
    id: 73,
    name: "Cafetière à piston 1L",
    category: "Cuisine",
    price: 24.99,
    emoji: "☕",
    badge: "Promo",
  },
  {
    id: 74,
    name: "Bol en céramique artisanal",
    category: "Cuisine",
    price: 12.5,
    emoji: "🥣",
  },
  {
    id: 75,
    name: "Épices du monde (coffret 6)",
    category: "Cuisine",
    price: 22.0,
    emoji: "🌶️",
    badge: "Nouveau",
  },
  {
    id: 76,
    name: "Bougie parfumée soja vanille",
    category: "Maison",
    price: 14.0,
    emoji: "🕯️",
  },
  {
    id: 77,
    name: "Savon artisanal lavande 100g",
    category: "Maison",
    price: 6.5,
    emoji: "🧼",
    badge: "Promo",
  },
  {
    id: 78,
    name: "Plante grasse en pot céramique",
    category: "Maison",
    price: 9.9,
    emoji: "🌵",
    badge: "Nouveau",
  },
  {
    id: 79,
    name: "Diffuseur huiles essentielles",
    category: "Maison",
    price: 34.0,
    emoji: "🌿",
  },
  {
    id: 80,
    name: "Panier tressé rangement",
    category: "Maison",
    price: 21.0,
    emoji: "🧺",
    badge: "Promo",
  },

  // --- Jeux & Loisirs ---
  {
    id: 81,
    name: "Jeu de cartes Blink",
    category: "Jeux",
    price: 8.9,
    emoji: "🃏",
    badge: "Promo",
  },
  {
    id: 82,
    name: "Rubik's Cube 3x3",
    category: "Jeux",
    price: 11.0,
    emoji: "🧊",
  },
  {
    id: 83,
    name: "Jeu d'échecs bois",
    category: "Jeux",
    price: 29.0,
    emoji: "♟️",
    badge: "Nouveau",
  },
  {
    id: 84,
    name: "Puzzle 1000 pièces paysage",
    category: "Jeux",
    price: 17.5,
    emoji: "🧩",
  },
  {
    id: 85,
    name: "Dés de jeu (lot 10)",
    category: "Jeux",
    price: 4.5,
    emoji: "🎲",
    badge: "Promo",
  },
  {
    id: 86,
    name: "Jeu de société Dobble",
    category: "Jeux",
    price: 13.0,
    emoji: "🎯",
  },
  {
    id: 87,
    name: "Figurine collector manga",
    category: "Jeux",
    price: 24.0,
    emoji: "🗿",
    badge: "Nouveau",
  },
  {
    id: 88,
    name: "Cartes Pokémon booster",
    category: "Jeux",
    price: 5.0,
    emoji: "🃏",
    badge: "Promo",
  },
  {
    id: 89,
    name: "Jeu de dominos classique",
    category: "Jeux",
    price: 12.0,
    emoji: "🀄",
  },
  {
    id: 90,
    name: "Toupie métal anti-stress",
    category: "Jeux",
    price: 7.9,
    emoji: "🌀",
  },

  // --- Mode & Accessoires ---
  {
    id: 91,
    name: "Bonnet laine mérinos",
    category: "Mode",
    price: 22.0,
    emoji: "🧢",
    badge: "Nouveau",
  },
  {
    id: 92,
    name: "Tote bag coton bio",
    category: "Mode",
    price: 9.9,
    emoji: "👜",
    badge: "Promo",
  },
  {
    id: 93,
    name: "Ceinture cuir véritable",
    category: "Mode",
    price: 35.0,
    emoji: "👔",
  },
  {
    id: 94,
    name: "Chaussettes fantaisie (lot 3)",
    category: "Mode",
    price: 12.0,
    emoji: "🧦",
    badge: "Nouveau",
  },
  {
    id: 95,
    name: "Lunettes de soleil UV400",
    category: "Mode",
    price: 19.0,
    emoji: "😎",
    badge: "Promo",
  },
  {
    id: 96,
    name: "Écharpe laine douce",
    category: "Mode",
    price: 28.0,
    emoji: "🧣",
  },
  {
    id: 97,
    name: "Porte-monnaie cuir zippé",
    category: "Mode",
    price: 18.0,
    emoji: "👛",
    badge: "Nouveau",
  },
  {
    id: 98,
    name: "Montre analogique minimaliste",
    category: "Mode",
    price: 59.0,
    emoji: "⌚",
    badge: "Promo",
  },
  {
    id: 99,
    name: "Broche émaillée fleur",
    category: "Mode",
    price: 8.5,
    emoji: "💐",
  },
  {
    id: 100,
    name: "Bracelet perles naturelles",
    category: "Mode",
    price: 14.0,
    emoji: "📿",
    badge: "Nouveau",
  },
]
